In [38]:
%config Completer.use_jedi = False

In [39]:
import welly
import lasio
import pandas as pd
from base import ROOT_DIR

In [40]:
las_files = (ROOT_DIR / "gtx/data/well_log_files/Clean_LAS").glob("*.las")

files = {}
a = 0
for las in las_files:
    header = welly.Well.from_las(las, index='ft')
    files['header' + str(a)] = header
    a += 1

In [ ]:
las_files = (ROOT_DIR / "gtx/data/well_log_files/Clean_LAS").glob("*.las")
df_las_all = pd.DataFrame()
uwi_col = "UWI"
basin_col = "basin"
for las_file in las_files:
    las = welly.Well.from_las(las_file, index='ft')
    las_df = las.df()
    uwi: str = las.uwi
    las_df[uwi_col] = uwi
    las_df[basin_col] = "Eaglebine" if uwi.startswith("42") else "Duvernay"
    df_las_all = df_las_all.append(las_df)
#df_las_all.to_csv("well_logs.csv")

In [51]:
df_las_all

,CALSED,CALWS,CONDWS,DRESWS,DTED,DTWS,GRSED,GRWS,ILDED,ILMED,...,AF90,AF10ED,AF90ED,DPHZED,TNPHED,CHTD,ARFL,ASGU,LL3ED,LL3
Depth,,,,,,,,,,,,,,,,,,,,,
950.0,9.6926,9.6926,230.2433,4.3433,140.0,140.0,NaN,NaN,4.3433,4.0338,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1000.0,8.3385,8.3385,67.4727,14.8208,140.0,140.0,NaN,NaN,14.8208,11.2619,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1050.0,9.4662,9.4662,170.1346,5.8777,NaN,NaN,NaN,NaN,5.8777,5.7302,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1100.0,10.6005,10.6005,234.4886,4.2646,NaN,NaN,NaN,NaN,4.2646,4.0496,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1150.0,11.3021,11.3021,194.5147,5.1410,NaN,NaN,NaN,NaN,5.1410,4.8778,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3700.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3750.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3800.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3850.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3900.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
df_las_all.to_csv("well_logs.csv")